CREATE TABLE IF NOT EXISTS users (
    `ID` INT(100) NOT NULL AUTOINCREMENT,
    `LOGIN` CHAR(255) NOT NULL,
    `PASSWORD` VARCHAR(65535) NOT NULL,
    `COMMENT` TEXT,
    `COMMENT2` BLOB,
    `BDATE` DATE DEFAULT CURRENT_DATE, //DATETIME, TIMESTAMP, TIME, YEAR(N), 
    `GENDER` ENUM(1) DEFAULT '1',
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS users;

INSERT INTO users (LOGIN, PASSWORD) VALUES ('admin', '123456');

DELETE FROM users WHERE ID=1;

SELECT * FROM users WHERE group=4;

SELECT LOGIN, NAME, AGE FROM users;

SELECT AGE * 365 AS DAYS, NAME, LOGIN FROM users;